<a href="https://colab.research.google.com/github/arifarman02/Learning_data_science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###Creating an array

In [ ]:
a = np.array([1, 2, 3])
print (a)

[1 2 3]


###Adding, removing and sorting elements

In [ ]:
#Sort array in ascending order
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr) 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Concatenate arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

###Shape and size of an array

In [ ]:
#To get dimensions of an array
a.ndim

1

In [ ]:
#To get the total number of elements in an array
a.size

4

In [ ]:
#To get the shape of the array
a.shape

(4,)

###Reshaping an array

In [ ]:
#Create an array containing six elements
a = np.arange(6)
print (a)

[0 1 2 3 4 5]


In [ ]:
#Reshape array a into an array with three rows and two columns
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
#This is used for optional parameters
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

###Converting 1D array into 2D array (adding axis)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
#np.newaxis will increase dimensions by one when used once
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
#1D array can be converted with a row or column vector using np.newaxis
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
#New axis can be inserted at a specified position with np.expand_dims
b = np.expand_dims(a, axis = 1) #Adding axis at position 1
b.shape

(6, 1)

In [ ]:
#Adding axis at index position 0
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

###Indexing and slicing

In [ ]:
#Arrays can be indexed and sliced the same way as lists in Python
data = np.array([1, 2, 3])
data [1]

2

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
#Selecting values from an array that fulfill certain conditions
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [ ]:
#Selecting numbers that are equal to or greater than 5, and use that condition to index and array
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
#Selecting elements that are divisible by 2
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
#Selecting elements that satisfy two conditions using & and |
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
#| returns bolean values
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
#np.nonzero() can be used to select elements or indices from an array
#To print indices of elements that are < than 5:
b = np.nonzero(a < 5)
print(b)
#First array represents the row indices where these values are found, the second the column indices where the values are found

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [ ]:
#To generate a list of coordinates where the elements exist, zip the arrays, iterate over the list of coordinates
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
  print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
#np.nonzero() can be used to print the elements in an array that are < 5
print(a[b])

[1 2 3 4]


In [ ]:
#If target is non existant in the array, then returned array of indices will be empty
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


###Create an array from existing data

In [ ]:
#A new array can be created from a section of an existing array by specifying where you want to slice your array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = a[3:8]
print (arr1)

[4 5 6 7 8]


In [ ]:
#Two existing arrays can be stacked both vertically and horizontally
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [ ]:
#Vertically
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
#Horizontally
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
#An array can be split into smaller arrays.
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [ ]:
#Splitting array into three equally shaped arrays
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
#To split after third and fourth column
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]), array([[ 4],
        [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
#View method can be used to create a new array object that looks at the same data (shallow copy)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
print (b1)

[1 2 3 4]


In [ ]:
b1[0] = 99
print (b1)

[99  2  3  4]


In [ ]:
print(a)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#Copy method can be used to make a complete copy of an array (deep copy)
b2 = a.copy()

###Basic array operations

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)

In [ ]:
#Addition
add = data + ones
print (add)

[2 3]


In [ ]:
#Subtraction
sub = data - ones
print (sub)

[0 1]


In [ ]:
#Multiplication
mul = data * data
print (mul)

[1 4]


In [ ]:
#Division
div = data/data
print (div)

[1. 1.]


In [ ]:
#To find sum
a = np.array([1, 2, 3, 4])
a.sum()

10

In [ ]:
#To add rows or columns in a 2D array
b = np.array([[1, 1], [2, 2]])

In [ ]:
#Rows
b.sum(axis = 0)

array([3, 3])

In [ ]:
#Columns
b.sum(axis = 1)

array([2, 4])

###Broadcasting

In [ ]:
#Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different types, e.g m to km
data = np.array([1.0, 2.0])
data * 1.6
print (data)

[1. 2.]


###More useful array operations

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
#To find sum
a.sum()

4.8595784

In [ ]:
#To find the smallest value
a.min()

0.05093587

In [ ]:
#To find the smallest value in each column
a.min(axis = 0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

###Creating matrices

In [ ]:
#Lists of lists create a 2-D array or matrix
data = np.array([[1, 2], [3, 4], [5, 6]])
print (data)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Indexing and slicing operations
data[0, 1]

array([1, 3])

In [19]:
data[0,1]

2

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
#Aggragate is done the same way as vectors
data.max()

6

In [ ]:
data.min()

1

In [ ]:
data.sum()

21

In [16]:
#Aggragation can be done across columns or rows
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)

[[1 2]
 [5 3]
 [4 6]]


In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 5, 6])

In [ ]:
#Matrices can be arithmatically operated on
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
#If one matrix has only one column or row broadcast rules will be applied
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
#ones(), zeros() and random allows us to initialize values of an array
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [ ]:
#2D arrays can also be intilized by giving the functions a tuple to describe the matrix
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
rng.random((3, 2))

array([[0.01652764, 0.81327024],
       [0.91275558, 0.60663578],
       [0.72949656, 0.54362499]])

###Generating random numbers

In [ ]:
#To generate 2x4 array of random integers between 0-4
rng.integers(5, size=(2, 4))

array([[2, 4, 1, 4],
       [3, 0, 1, 4]])

###How to get unique items and counts

In [2]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [3]:
#To get unique value
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [4]:
#To get indices of the unique values
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [5]:
#To get frequency of unique values
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [6]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [7]:
#Same principles are applied to 2D arrays
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
#To get unique rows and columns
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
#To get uniques rows, indices and occurrence
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts = True, return_index=True)

In [12]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(indices)

[0 1 2]


In [14]:
print(occurrence_count)

[2 1 1]


###Transposing and reshaping a matrix

In [17]:
data.reshape(2, 3) #data is defined in Creating matrices chapter

array([[1, 2, 5],
       [3, 4, 6]])

In [18]:
data.reshape(3, 2)

array([[1, 2],
       [5, 3],
       [4, 6]])

In [23]:
arr = np.arange(6).reshape((2, 3))
(arr)

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
#To transpose
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [24]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

###How to reverse an array

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
#To reverse
reversed_arr = np.flip(arr)
print(reversed_arr)

[8 7 6 5 4 3 2 1]


In [30]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [32]:
#Same for 2D arrays
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [33]:
#To reverse rows
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [36]:
#To reverse columns
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [38]:
#To reverse only 1 row
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
#To reverse only 1 column
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


###Reshaping and flattening multidimensional arrays